import { GoogleGenAI, Type } from "@google/genai";

// Helper to check and prompt for API Key selection
export const checkAndEnsureApiKey = async (): Promise<boolean> => {
  const win = window as any;
  if (win.aistudio && win.aistudio.hasSelectedApiKey) {
    const hasKey = await win.aistudio.hasSelectedApiKey();
    if (!hasKey) {
      if (win.aistudio.openSelectKey) {
        await win.aistudio.openSelectKey();
        return true; // Assume success after modal interaction due to race condition guidance
      }
      return false;
    }
    return true;
  }
  // Fallback for dev environments without the special window object
  return true;
};

export const generateTryOnImage = async (
  faceImageBase64: string,
  clothImageBase64: string
): Promise<string> => {
  await checkAndEnsureApiKey();
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const cleanFace = faceImageBase64.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, "");
  const cleanCloth = clothImageBase64.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, "");

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            text: "Generate a high-quality, photorealistic image of the person in the first image wearing the clothing item shown in the second image. The person's facial features, skin tone, and body shape must match the first image exactly. The clothing should fit naturally. The background should be neutral and clean. High fashion photography style."
          },
          { inlineData: { mimeType: 'image/png', data: cleanFace } },
          { inlineData: { mimeType: 'image/png', data: cleanCloth } }
        ]
      },
      config: {
        imageConfig: {
          aspectRatio: "3:4",
          // imageSize is not supported by gemini-2.5-flash-image, removed.
        }
      }
    });

    if (response.candidates && response.candidates.length > 0) {
      const parts = response.candidates[0].content.parts;
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by the model.");
  } catch (error: any) {
    console.error("Gemini Generation Error:", error);
    const win = window as any;
    if (
      (error.message?.includes("Requested entity was not found") || 
       error.status === 403 || 
       error.message?.includes("PERMISSION_DENIED")) && 
      win.aistudio?.openSelectKey
    ) {
       await win.aistudio.openSelectKey();
       throw new Error("API Key issue detected. Please re-select your key and try again.");
    }
    throw error;
  }
};

export const getStyleRecommendations = async (
  faceImageBase64: string,
  clothImageBase64: string
): Promise<any> => {
  await checkAndEnsureApiKey();
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const cleanFace = faceImageBase64.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, "");
  const cleanCloth = clothImageBase64.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, "");

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: {
        parts: [
          { 
            text: `You are a top fashion stylist for the modern Indian market (Gen Z and Millennials). 
                   Analyze the user's face (skin tone, shape) from the first image and the clothing item from the second image.
                   Provide a style analysis and 3 specific recommendations for accessories, bottoms, or footwear that would complete this look.
                   Keep the tone exciting, futuristic, and helpful.`
          },
          { inlineData: { mimeType: 'image/png', data: cleanFace } },
          { inlineData: { mimeType: 'image/png', data: cleanCloth } }
        ]
      },
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            analysis: { type: Type.STRING },
            suggestions: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  item: { type: Type.STRING },
                  reason: { type: Type.STRING },
                  color: { type: Type.STRING },
                }
              }
            }
          }
        }
      }
    });

    return JSON.parse(response.text || "{}");
  } catch (error: any) {
    console.error("Style Recommendation Error:", error);
    const win = window as any;
    if (
      (error.message?.includes("Requested entity was not found") || 
       error.status === 403 || 
       error.message?.includes("PERMISSION_DENIED")) && 
      win.aistudio?.openSelectKey
    ) {
       await win.aistudio.openSelectKey();
    }
    throw new Error("Could not generate style advice.");
  }
};